### ISSUE TITLE
Version of the used libs

### ISSUE THREAD

**Issue by caiy0220** [orestislampridis/X-SPELLS#1]
Hello!
I found the repository via the link provided in your paper, which is really an interesting work and thanks a lot for sharing.
But I ran into some problems while learning the code. For example, the reconstructed texts do not seem to be similar to the original inputs. Could this be caused by the different running environment?
Following is my setup:
- System: Ubuntu 18.04
- Python 3.6
- Tensorflow: 2.1.0
- Keras: 2.3.1
It would be so nice if you can give me some advices.

**Comment by orestislampridis** [comment]
Hello, thank you for your interest and sorry for the very late reply!

There were some problems in the code and indeed didn't output the same text for the reconstructed and the original. Namely, the number of epochs was lower. Also I have added the requirements.txt file so you can cross check with your versions.

**Comment by caiy0220** [comment]
Thank you so much for your reply.
